### ISSUE TITLE
Windows 10 compatibility 

### ISSUE THREAD

**Issue by gferreroferri** [valx76/WeekTray#1]
I opened the app in Windows 10 and nothing happened

**Comment by valx76** [comment]
Do you have .NET Desktop Runtime (x64) installed?
Otherwise, it may be in the hidden icon

I've tested on Windows 10/11, it is working fine

**Comment by gferreroferri** [comment]
No

El 15 jun 2022, a las 11:54, Valentin PONS ***@***.***> escribió:

﻿

Do you have .NET Desktop Runtime (x64) installed?

**Comment by gferreroferri** [comment]
Now I installed the 6.0.6 for windows runtime but still not working

El 15 jun 2022, a las 11:54, Valentin PONS ***@***.***> escribió:

﻿

Do you have .NET Desktop Runtime (x64) installed?

**Comment by gferreroferri** [comment]
Now I got it working. My antivirus was putting the file in quarantine

El 15 jun 2022, a las 12:08, Guillermo Ferrero Ferri ***@***.***> escribió:

﻿
No

El 15 jun 2022, a las 11:54, Valentin PONS ***@***.***> escribió:

﻿

Do you have .NET Desktop Runtime (x64) installed?

**Comment by valx76** [comment]
Good news, thanks for reporting :)
