### ISSUE TITLE
Suggestion: month calendar with week numbers when clicked

### ISSUE THREAD

**Issue by gferreroferri** [valx76/WeekTray#3]
It would be great if app would show a month calendar with week numbers when clicked on the taskbar. Also be able to go back and forth in the months

**Comment by valx76** [comment]
This is out of scope
If you need a more advanced calendar, you can probably check https://github.com/White-Tiger/T-Clock which is probably more what you're looking for.

**Comment by gferreroferri** [comment]
Ok. Understood. Thanks for the tip

El 29 ago 2022, a las 17:32, Valentin PONS ***@***.***> escribió:

﻿

This is out of scope
If you need a more advanced calendar, you can probably check https://github.com/White-Tiger/T-Clock which is probably more what you're looking for.
