### ISSUE TITLE
Text not sharp

### ISSUE THREAD

**Issue by gferreroferri** [valx76/WeekTray#4]
See screenshot. For some screen resolutions (in this case 1920x1200 screen with 125% text scaling) the text does not look very sharp. Is there any way to improve readability? I have selected white background RGB 255 255 255 with black text RGB 000 000 000
Thanks!

![Screenshot 2022-08-31 154627](https://user-images.githubusercontent.com/823394/187681902-93fe8d59-d358-48b9-9fe3-851071b36569.png)

**Comment by valx76** [comment]
Could you please try the file attached and let me know if this is better?
If yes, I'll post the sources and make a new release

Thanks for reporting!
[WeekTray-font-blurry-fix-attempt.zip](https://github.com/valx76/WeekTray/files/9484431/WeekTray-font-blurry-fix-attempt.zip)

**Comment by gferreroferri** [comment]
Hi,

See screenshot. Still quite similar. Somehow it does not render with full pixel resolution.
[cid:5960f53e-8e44-44c9-8b07-bd636fbb480c]
________________________________

**Comment by gferreroferri** [comment]
Also the configuration window looks like this:
[cid:45ba7abd-49b4-487e-9818-264dbfbaf15d]
________________________________

**Comment by valx76** [comment]
Your pictures didn't get uploaded

**Comment by gferreroferri** [comment]
![image-1](https://user-images.githubusercontent.com/823394/188391044-fce75429-d47e-462b-abc1-3ee2cae8044e.png)
![image](https://user-images.githubusercontent.com/823394/188391057-47300ac1-56c5-49bb-811b-fad906ca6378.png)
